// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOLoSeMaUM2vv6vEJ_qpKDnkAbu6k19zY',
    appId: '1:562158796511:web:dc82938b914ae654fa336a',
    messagingSenderId: '562158796511',
    projectId: 'moapp-final-3d9c0',
    authDomain: 'moapp-final-3d9c0.firebaseapp.com',
    storageBucket: 'moapp-final-3d9c0.firebasestorage.app',
    measurementId: 'G-30T2F0YQ1M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5xq_xVl7_aXTl5BGJtL7EzSLLqVI9tj8',
    appId: '1:562158796511:android:2dae9083ff5a39edfa336a',
    messagingSenderId: '562158796511',
    projectId: 'moapp-final-3d9c0',
    storageBucket: 'moapp-final-3d9c0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvZIDTEXO4mE-jg26gGQdXXBe6OHLJODA',
    appId: '1:562158796511:ios:ee296743878b348efa336a',
    messagingSenderId: '562158796511',
    projectId: 'moapp-final-3d9c0',
    storageBucket: 'moapp-final-3d9c0.firebasestorage.app',
    iosClientId: '562158796511-4pn01gtrtaj4henu48vprsnphjpjl648.apps.googleusercontent.com',
    iosBundleId: 'com.example.my-moapp-final',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvZIDTEXO4mE-jg26gGQdXXBe6OHLJODA',
    appId: '1:562158796511:ios:f2986b3dcd212452fa336a',
    messagingSenderId: '562158796511',
    projectId: 'moapp-final-3d9c0',
    storageBucket: 'moapp-final-3d9c0.firebasestorage.app',
    iosClientId: '562158796511-l1eo9eqfsfs3jkatev07rgcpbogdnsk1.apps.googleusercontent.com',
    iosBundleId: 'com.example.mdc100Series',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOLoSeMaUM2vv6vEJ_qpKDnkAbu6k19zY',
    appId: '1:562158796511:web:abe5625422250c69fa336a',
    messagingSenderId: '562158796511',
    projectId: 'moapp-final-3d9c0',
    authDomain: 'moapp-final-3d9c0.firebaseapp.com',
    storageBucket: 'moapp-final-3d9c0.firebasestorage.app',
    measurementId: 'G-VX0SCPV24T',
  );

}